Add license header
Al2Klimov/trainee-go-cut pull request #19
Opened 2020-05-14 13:46 UTC by justinmueller05082000

fixes #18

2020-05-14 14:15 UTC, Al2Klimov requested changes

2020-05-14 14:15 UTC, Al2Klimov commented on main.go
> +// sort | (c) 2020 NETWAYS GmbH | GPLv2+
Srsly?

2020-05-14 14:28 UTC, justinmueller05082000 commented on main.go
> +// sort | (c) 2020 NETWAYS GmbH | GPLv2+
eh my brain is not working properly

2020-05-14 14:30 UTC, Al2Klimov requested changes
* [x] `git reset --soft HEAD~$(git rev-list --count $(git merge-base HEAD feature/add-copying-file-9)..HEAD^)`
* [x] `git commit --amend --no-edit`
* [x] `git push -f origin bugfix/add-license-header-18`

2020-05-15 08:05 UTC, Al2Klimov approved these changes

2020-05-15 08:05 UTC, merged